# ==============================================================================
# Auto-generated Python 3.x code transpiled from BLang
# Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)
# Target: Python 3.8+ Runtime Environment (AI, Scientific Computing, Backend)
# ==============================================================================
import sys
import math

# Runtime helper: Strict Type Safety Enforcer
def _bl_strict_add(a, b):
    if (isinstance(a, str) and isinstance(b, (int, float))) or (isinstance(a, (int, float)) and isinstance(b, str)):
        raise TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +')
    return a + b

# --- Transpiled Program Statements ---
def power(bl_at_base, bl_dollar_exponent):
    _result = 1
    _count = 0
    while (_count < bl_dollar_exponent):
        _result = (_result * bl_at_base)
        _count += 1
    return _result

def factorial(bl_dollar_n):
    if (bl_dollar_n <= 1):
        return 1
    _accum = 1
    _k = 2
    while (_k <= bl_dollar_n):
        _accum = (_accum * _k)
        _k += 1
    return _accum

def clamp(bl_dollar_val, bl_dollar_min_val, bl_dollar_max_val):
    if (bl_dollar_val < bl_dollar_min_val):
        return bl_dollar_min_val
    if (bl_dollar_val > bl_dollar_max_val):
        return bl_dollar_max_val
    return bl_dollar_val

print('>>> [math_lib.bl] Mathematical utilities loaded successfully!')
