// ==============================================================================
// Auto-generated JavaScript (ES6+) code transpiled from BLang
// Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)
// Target: Modern Web Browsers & Node.js Runtime (Web, Apps, Casual Games)
// ==============================================================================
'use strict';

// Runtime helper: Strict Type Safety Enforcer (No coercion between string and number in arithmetic)
function _bl_strict_add(a, b) {
    if ((typeof a === 'string' && typeof b === 'number') || (typeof a === 'number' && typeof b === 'string')) {
        throw new TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +');
    }
    return a + b;
}

// --- Transpiled Program Statements ---
function power(_at_base, $exponent) {
    let _result = 1;
    let _count = 0;
    while ((_count < $exponent)) {
        _result = (_result * _at_base);
        _count += 1;
    }
    return _result;
}

function factorial($n) {
    if (($n <= 1)) {
        return 1;
    }
    let _accum = 1;
    let _k = 2;
    while ((_k <= $n)) {
        _accum = (_accum * _k);
        _k += 1;
    }
    return _accum;
}

function clamp($val, $min_val, $max_val) {
    if (($val < $min_val)) {
        return $min_val;
    }
    if (($val > $max_val)) {
        return $max_val;
    }
    return $val;
}

console.log(">>> [math_lib.bl] Mathematical utilities loaded successfully!");
