// ==============================================================================
// Auto-generated JavaScript (ES6+) code transpiled from BLang
// Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)
// Target: Modern Web Browsers & Node.js Runtime (Web, Apps, Casual Games)
// ==============================================================================
'use strict';

// Runtime helper: Strict Type Safety Enforcer (No coercion between string and number in arithmetic)
function _bl_strict_add(a, b) {
    if ((typeof a === 'string' && typeof b === 'number') || (typeof a === 'number' && typeof b === 'string')) {
        throw new TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +');
    }
    return a + b;
}

// Runtime helper: Math & Geometry Standard Functions
const PI = Math.PI;
const E = Math.E;
// Trigonometry (Degrees by default)
const sin = (d) => Math.sin(d * (Math.PI / 180));
const cos = (d) => Math.cos(d * (Math.PI / 180));
const tan = (d) => Math.tan(d * (Math.PI / 180));
const cotan = (d) => 1 / Math.tan(d * (Math.PI / 180));
const cot = cotan;
const sind = sin;
const cosd = cos;
const tand = tan;
const cotand = cotan;
const sin_rad = (r) => Math.sin(r);
const cos_rad = (r) => Math.cos(r);
const tan_rad = (r) => Math.tan(r);
const cotan_rad = (r) => 1 / Math.tan(r);
const deg_to_rad = (d) => d * (Math.PI / 180);
const rad_to_deg = (r) => r * (180 / Math.PI);
const log = (x, base) => (base !== undefined ? Math.log(x) / Math.log(base) : Math.log10(x));
const ln = (x) => Math.log(x);
const log10 = (x) => Math.log10(x);
const log2 = (x) => Math.log2(x);
const sqrt = (x) => Math.sqrt(x);
const cbrt = (x) => Math.cbrt(x);
const root = (x, n) => Math.pow(x, 1 / n);
const pow = (b, e) => Math.pow(b, e);
const power = pow;
// Geometry: Circle (circle / cir, c / C / perimeter, s / S / area)
const circle_c = (r) => 2 * Math.PI * r;
const circle_C = circle_c;
const cir_c = circle_c;
const cir_C = circle_c;
const circle_perimeter = circle_c;
const cir_perimeter = circle_c;
const circle_circumference = circle_c;
const cir_circumference = circle_c;
const circle_s = (r) => Math.PI * r * r;
const circle_S = circle_s;
const cir_s = circle_s;
const cir_S = circle_s;
const circle_area = circle_s;
const cir_area = circle_s;
// Geometry: Sphere
const sphere_v = (r) => (4 / 3) * Math.PI * Math.pow(r, 3);
const sphere_V = sphere_v;
const sphere_volume = sphere_v;
const sphere_s = (r) => 4 * Math.PI * Math.pow(r, 2);
const sphere_S = sphere_s;
const sphere_area = sphere_s;
// Geometry: Cylinder
const cylinder_v = (r, h) => Math.PI * r * r * h;
const cylinder_V = cylinder_v;
const cylinder_volume = cylinder_v;
// Geometry: Cone
const cone_v = (r, h) => (1 / 3) * Math.PI * r * r * h;
const cone_V = cone_v;
const cone_volume = cone_v;
// Geometry: Square (square / sq, c / C / perimeter, s / S / area)
const square_c = (a) => 4 * a;
const square_C = square_c;
const sq_c = square_c;
const sq_C = square_c;
const square_perimeter = square_c;
const sq_perimeter = square_c;
const square_s = (a) => a * a;
const square_S = square_s;
const sq_s = square_s;
const sq_S = square_s;
const square_area = square_s;
const sq_area = square_s;
// Geometry: Cube
const cube_v = (a) => Math.pow(a, 3);
const cube_V = cube_v;
const cube_volume = cube_v;
const cube_s = (a) => 6 * a * a;
const cube_S = cube_s;
const cube_area = cube_s;
// Geometry: Rectangle (rect / rectangle, c / C / perimeter, s / S / area)
const rect_c = (w, h) => 2 * (w + h);
const rect_C = rect_c;
const rectangle_c = rect_c;
const rectangle_C = rect_c;
const rect_perimeter = rect_c;
const rectangle_perimeter = rect_c;
const rect_s = (w, h) => w * h;
const rect_S = rect_s;
const rectangle_s = rect_s;
const rectangle_S = rect_s;
const rect_area = rect_s;
const rectangle_area = rect_s;
// Geometry: Cuboid
const cuboid_v = (w, h, d) => w * h * d;
const cuboid_V = cuboid_v;
const cuboid_volume = cuboid_v;
// Geometry: Trapezoid
const trapezoid_s = (a, b, h) => ((a + b) * h) / 2;
const trapezoid_S = trapezoid_s;
const trapezoid_area = trapezoid_s;
const trapezoid_c = (a, b, c, d) => a + b + c + d;
const trapezoid_C = trapezoid_c;
const trapezoid_perimeter = trapezoid_c;
// Geometry: Regular Polygon
const polygon_c = (n, s) => n * s;
const polygon_C = polygon_c;
const polygon_perimeter = polygon_c;
const polygon_s = (n, s) => (n * s * s) / (4 * Math.tan(Math.PI / n));
const polygon_S = polygon_s;
const polygon_area = polygon_s;
// Geometry: Triangle (triangle / tri, c / C / perimeter, s / S / area)
const triangle_s = (b, h) => 0.5 * b * h;
const triangle_S = triangle_s;
const triangle_area = triangle_s;
const tri_s = triangle_s;
const tri_S = triangle_s;
const tri_area = triangle_s;
const triangle_c = (a, b, c) => a + b + c;
const triangle_C = triangle_c;
const triangle_perimeter = triangle_c;
const tri_c = triangle_c;
const tri_C = triangle_c;
const tri_perimeter = triangle_c;

// --- Transpiled Program Statements ---
console.log("==================================================");
console.log(">>> BLANG ADVANCED MATH & GEOMETRY CALCULATION <<<");
console.log("==================================================");
let _at_val_e = E;
let _at_ln_result = ln(_at_val_e);
let $log10_val = log(1000);
let $log2_val = log(64, 2);
console.log("--- 1. LOGARITHM & EXPONENTIAL ---");
console.log("ln(e)              =", _at_ln_result);
console.log("log10(1000)        =", $log10_val);
console.log("log2(64)           =", $log2_val);
let _at_can_bac_2 = sqrt(144);
let _at_can_bac_3 = cbrt(125);
let _at_can_bac_4 = root(81, 4);
let $luy_thua = pow(2, 10);
console.log("--- 2. ROOTS & POWERS ---");
console.log("sqrt(144)          =", _at_can_bac_2);
console.log("cbrt(125)          =", _at_can_bac_3);
console.log("root(81, 4)        =", _at_can_bac_4);
console.log("pow(2, 10)         =", $luy_thua);
let _at_sin_90 = sin(90);
let _at_cos_60 = cos(60);
let _at_tan_45 = tan(45);
let _at_cot_45 = cotan(45);
console.log("--- 3. TRIGONOMETRY (G\u00d3C & L\u01af\u1ee2NG GI\u00c1C THEO \u0110\u1ed8) ---");
console.log("sin(90 \u0111\u1ed9)         =", _at_sin_90);
console.log("cos(60 \u0111\u1ed9)         =", _at_cos_60);
console.log("tan(45 \u0111\u1ed9)         =", _at_tan_45);
console.log("cotan(45 \u0111\u1ed9)       =", _at_cot_45);
let _at_ban_kinh = 5;
let _chu_vi_tron = cir_c(_at_ban_kinh);
let _dien_tich_tron = cir_s(_at_ban_kinh);
let _the_tich_cau = sphere_v(3);
let _the_tich_tru = cylinder_v(3, 10);
let _the_tich_non = cone_v(3, 10);
console.log("--- 4. H\u00ccNH TR\u00d2N, C\u1ea6U, TR\u1ee4, N\u00d3N ---");
console.log("Chu vi h\u00ecnh tr\u00f2n (cir_c, r=5)       =", _chu_vi_tron);
console.log("Di\u1ec7n t\u00edch h\u00ecnh tr\u00f2n (cir_s, r=5)    =", _dien_tich_tron);
console.log("Th\u1ec3 t\u00edch h\u00ecnh c\u1ea7u (sphere_v, r=3)   =", _the_tich_cau);
console.log("Th\u1ec3 t\u00edch h\u00ecnh tr\u1ee5 (cylinder_v, r=3) =", _the_tich_tru);
console.log("Th\u1ec3 t\u00edch h\u00ecnh n\u00f3n (cone_v, r=3, h=10)=", _the_tich_non);
let _at_canh_vuong = 6;
let _chu_vi_vuong = sq_c(_at_canh_vuong);
let _dien_tich_vuong = sq_s(_at_canh_vuong);
let _the_tich_lap_phuong = cube_v(4);
console.log("--- 5. H\u00ccNH VU\u00d4NG & L\u1eacP PH\u01af\u01a0NG ---");
console.log("Chu vi h\u00ecnh vu\u00f4ng (sq_c, a=6)      =", _chu_vi_vuong);
console.log("Di\u1ec7n t\u00edch h\u00ecnh vu\u00f4ng (sq_s, a=6)   =", _dien_tich_vuong);
console.log("Th\u1ec3 t\u00edch l\u1eadp ph\u01b0\u01a1ng (cube_v, a=4)  =", _the_tich_lap_phuong);
let _chu_vi_cn = rect_c(8, 5);
let _dien_tich_cn = rect_s(8, 5);
let _the_tich_hop = cuboid_v(4, 5, 6);
console.log("--- 6. H\u00ccNH CH\u1eee NH\u1eacT & H\u00ccNH H\u1ed8P ---");
console.log("Chu vi h\u00ecnh ch\u1eef nh\u1eadt (rect_c, 8x5)   =", _chu_vi_cn);
console.log("Di\u1ec7n t\u00edch h\u00ecnh ch\u1eef nh\u1eadt (rect_s, 8x5)=", _dien_tich_cn);
console.log("Th\u1ec3 t\u00edch h\u00ecnh h\u1ed9p (cuboid_v, 4x5x6)  =", _the_tich_hop);
let _dien_tich_thang = trapezoid_s(6, 10, 4);
let _chu_vi_thang = trapezoid_c(6, 10, 5, 5);
let _chu_vi_luc_giac = polygon_c(6, 4);
let _dien_tich_luc_giac = polygon_s(6, 4);
console.log("--- 7. H\u00ccNH THANG & \u0110A GI\u00c1C \u0110\u1ec0U ---");
console.log("Di\u1ec7n t\u00edch h\u00ecnh thang (trapezoid_s)   =", _dien_tich_thang);
console.log("Chu vi h\u00ecnh thang (trapezoid_c)      =", _chu_vi_thang);
console.log("Chu vi l\u1ee5c gi\u00e1c \u0111\u1ec1u (polygon_c)     =", _chu_vi_luc_giac);
console.log("Di\u1ec7n t\u00edch l\u1ee5c gi\u00e1c \u0111\u1ec1u (polygon_s)  =", _dien_tich_luc_giac);
let _chu_vi_tam_giac = tri_c(3, 4, 5);
let _dien_tich_tam_giac = tri_s(6, 4);
console.log("--- 8. H\u00ccNH TAM GI\u00c1C (TRI / TRIANGLE) ---");
console.log("Chu vi tam gi\u00e1c (tri_c, 3, 4, 5)    =", _chu_vi_tam_giac);
console.log("Di\u1ec7n t\u00edch tam gi\u00e1c (tri_s, b=6, h=4)=", _dien_tich_tam_giac);
console.log("==================================================");
console.log(">>> T\u1ea4T C\u1ea2 C\u00c1C PH\u00c9P T\u00cdNH TO\u00c1N H\u1eccC \u0110\u00c3 HO\u00c0N TH\u00c0NH <<<");
console.log("==================================================");
