// ==============================================================================
// Auto-generated JavaScript (ES6+) code transpiled from BLang
// Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)
// Target: Modern Web Browsers & Node.js Runtime (Web, Apps, Casual Games)
// ==============================================================================
'use strict';

// Runtime helper: Strict Type Safety Enforcer (No coercion between string and number in arithmetic)
function _bl_strict_add(a, b) {
    if ((typeof a === 'string' && typeof b === 'number') || (typeof a === 'number' && typeof b === 'string')) {
        throw new TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +');
    }
    return a + b;
}

// Runtime helper: Math & Geometry Standard Functions
const PI = Math.PI;
const E = Math.E;
const sin = (x) => Math.sin(x);
const cos = (x) => Math.cos(x);
const tan = (x) => Math.tan(x);
const cotan = (x) => 1 / Math.tan(x);
const cot = cotan;
const deg_to_rad = (d) => d * (Math.PI / 180);
const rad_to_deg = (r) => r * (180 / Math.PI);
const sind = (d) => Math.sin(d * (Math.PI / 180));
const cosd = (d) => Math.cos(d * (Math.PI / 180));
const tand = (d) => Math.tan(d * (Math.PI / 180));
const cotand = (d) => 1 / Math.tan(d * (Math.PI / 180));
const log = (x, base) => (base !== undefined ? Math.log(x) / Math.log(base) : Math.log10(x));
const ln = (x) => Math.log(x);
const log10 = (x) => Math.log10(x);
const log2 = (x) => Math.log2(x);
const sqrt = (x) => Math.sqrt(x);
const cbrt = (x) => Math.cbrt(x);
const root = (x, n) => Math.pow(x, 1 / n);
const pow = (b, e) => Math.pow(b, e);
const power = pow;
const circle_perimeter = (r) => 2 * Math.PI * r;
const circle_circumference = circle_perimeter;
const circle_area = (r) => Math.PI * r * r;
const sphere_volume = (r) => (4 / 3) * Math.PI * Math.pow(r, 3);
const cylinder_volume = (r, h) => Math.PI * r * r * h;
const cone_volume = (r, h) => (1 / 3) * Math.PI * r * r * h;
const square_perimeter = (a) => 4 * a;
const square_area = (a) => a * a;
const cube_volume = (a) => Math.pow(a, 3);
const rect_perimeter = (w, h) => 2 * (w + h);
const rect_area = (w, h) => w * h;
const cuboid_volume = (w, h, d) => w * h * d;
const trapezoid_area = (a, b, h) => ((a + b) * h) / 2;
const trapezoid_perimeter = (a, b, c, d) => a + b + c + d;
const polygon_perimeter = (n, s) => n * s;
const polygon_area = (n, s) => (n * s * s) / (4 * Math.tan(Math.PI / n));
const triangle_area = (b, h) => 0.5 * b * h;
const triangle_perimeter = (a, b, c) => a + b + c;

// --- Transpiled Program Statements ---
console.log("==================================================");
console.log(">>> BLANG ADVANCED MATH & GEOMETRY CALCULATION <<<");
console.log("==================================================");
let _at_val_e = E;
let _at_ln_result = ln(_at_val_e);
let $log10_val = log(1000);
let $log2_val = log(64, 2);
console.log("--- 1. LOGARITHM & EXPONENTIAL ---");
console.log("ln(e)              =", _at_ln_result);
console.log("log10(1000)        =", $log10_val);
console.log("log2(64)           =", $log2_val);
let _at_can_bac_2 = sqrt(144);
let _at_can_bac_3 = cbrt(125);
let _at_can_bac_4 = root(81, 4);
let $luy_thua = pow(2, 10);
console.log("--- 2. ROOTS & POWERS ---");
console.log("sqrt(144)          =", _at_can_bac_2);
console.log("cbrt(125)          =", _at_can_bac_3);
console.log("root(81, 4)        =", _at_can_bac_4);
console.log("pow(2, 10)         =", $luy_thua);
let _at_sin_90 = sind(90);
let _at_cos_60 = cosd(60);
let _at_tan_45 = tand(45);
let _at_cot_45 = cotand(45);
console.log("--- 3. TRIGONOMETRY (G\u00d3C & L\u01af\u1ee2NG GI\u00c1C) ---");
console.log("sin(90 deg)        =", _at_sin_90);
console.log("cos(60 deg)        =", _at_cos_60);
console.log("tan(45 deg)        =", _at_tan_45);
console.log("cotan(45 deg)      =", _at_cot_45);
let _at_ban_kinh = 5;
let _chu_vi_tron = circle_perimeter(_at_ban_kinh);
let _dien_tich_tron = circle_area(_at_ban_kinh);
let _the_tich_cau = sphere_volume(3);
let _the_tich_tru = cylinder_volume(3, 10);
let _the_tich_non = cone_volume(3, 10);
console.log("--- 4. H\u00ccNH TR\u00d2N, C\u1ea6U, TR\u1ee4, N\u00d3N ---");
console.log("Chu vi h\u00ecnh tr\u00f2n (r=5)       =", _chu_vi_tron);
console.log("Di\u1ec7n t\u00edch h\u00ecnh tr\u00f2n (r=5)    =", _dien_tich_tron);
console.log("Th\u1ec3 t\u00edch h\u00ecnh c\u1ea7u (r=3)      =", _the_tich_cau);
console.log("Th\u1ec3 t\u00edch h\u00ecnh tr\u1ee5 (r=3, h=10)=", _the_tich_tru);
console.log("Th\u1ec3 t\u00edch h\u00ecnh n\u00f3n (r=3, h=10)=", _the_tich_non);
let _at_canh_vuong = 6;
let _chu_vi_vuong = square_perimeter(_at_canh_vuong);
let _dien_tich_vuong = square_area(_at_canh_vuong);
let _the_tich_lap_phuong = cube_volume(4);
console.log("--- 5. H\u00ccNH VU\u00d4NG & L\u1eacP PH\u01af\u01a0NG ---");
console.log("Chu vi h\u00ecnh vu\u00f4ng (a=6)      =", _chu_vi_vuong);
console.log("Di\u1ec7n t\u00edch h\u00ecnh vu\u00f4ng (a=6)   =", _dien_tich_vuong);
console.log("Th\u1ec3 t\u00edch l\u1eadp ph\u01b0\u01a1ng (a=4)    =", _the_tich_lap_phuong);
let _chu_vi_cn = rect_perimeter(8, 5);
let _dien_tich_cn = rect_area(8, 5);
let _the_tich_hop = cuboid_volume(4, 5, 6);
console.log("--- 6. H\u00ccNH CH\u1eee NH\u1eacT & H\u00ccNH H\u1ed8P ---");
console.log("Chu vi h\u00ecnh ch\u1eef nh\u1eadt (8x5)   =", _chu_vi_cn);
console.log("Di\u1ec7n t\u00edch h\u00ecnh ch\u1eef nh\u1eadt (8x5)=", _dien_tich_cn);
console.log("Th\u1ec3 t\u00edch h\u00ecnh h\u1ed9p (4x5x6)    =", _the_tich_hop);
let _dien_tich_thang = trapezoid_area(6, 10, 4);
let _chu_vi_thang = trapezoid_perimeter(6, 10, 5, 5);
let _chu_vi_luc_giac = polygon_perimeter(6, 4);
let _dien_tich_luc_giac = polygon_area(6, 4);
console.log("--- 7. H\u00ccNH THANG & \u0110A GI\u00c1C \u0110\u1ec0U ---");
console.log("Di\u1ec7n t\u00edch h\u00ecnh thang (6, 10, h=4)   =", _dien_tich_thang);
console.log("Chu vi h\u00ecnh thang (6, 10, 5, 5)     =", _chu_vi_thang);
console.log("Chu vi l\u1ee5c gi\u00e1c \u0111\u1ec1u (n=6, s=4)      =", _chu_vi_luc_giac);
console.log("Di\u1ec7n t\u00edch l\u1ee5c gi\u00e1c \u0111\u1ec1u (n=6, s=4)   =", _dien_tich_luc_giac);
console.log("==================================================");
console.log(">>> T\u1ea4T C\u1ea2 C\u00c1C PH\u00c9P T\u00cdNH TO\u00c1N H\u1eccC \u0110\u00c3 HO\u00c0N TH\u00c0NH <<<");
console.log("==================================================");
