# ==============================================================================
# Auto-generated Python 3.x code transpiled from BLang
# Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)
# Target: Python 3.8+ Runtime Environment (AI, Scientific Computing, Backend)
# ==============================================================================
import sys
import math

# Runtime helper: Strict Type Safety Enforcer
def _bl_strict_add(a, b):
    if (isinstance(a, str) and isinstance(b, (int, float))) or (isinstance(a, (int, float)) and isinstance(b, str)):
        raise TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +')
    return a + b

# Runtime helper: Math & Geometry Standard Functions
PI = math.pi
E = math.e
sin = math.sin
cos = math.cos
tan = math.tan
cotan = lambda x: 1.0 / math.tan(x)
cot = cotan
deg_to_rad = lambda d: d * (math.pi / 180.0)
rad_to_deg = lambda r: r * (180.0 / math.pi)
sind = lambda d: math.sin(d * (math.pi / 180.0))
cosd = lambda d: math.cos(d * (math.pi / 180.0))
tand = lambda d: math.tan(d * (math.pi / 180.0))
cotand = lambda d: 1.0 / math.tan(d * (math.pi / 180.0))
log = lambda x, base=10: math.log(x, base)
ln = math.log
log10 = math.log10
log2 = math.log2
sqrt = math.sqrt
cbrt = lambda x: x ** (1.0 / 3.0)
root = lambda x, n: x ** (1.0 / n)
pow = math.pow
power = pow
circle_perimeter = lambda r: 2.0 * math.pi * r
circle_circumference = circle_perimeter
circle_area = lambda r: math.pi * (r ** 2)
sphere_volume = lambda r: (4.0 / 3.0) * math.pi * (r ** 3)
cylinder_volume = lambda r, h: math.pi * (r ** 2) * h
cone_volume = lambda r, h: (1.0 / 3.0) * math.pi * (r ** 2) * h
square_perimeter = lambda a: 4.0 * a
square_area = lambda a: float(a * a)
cube_volume = lambda a: float(a ** 3)
rect_perimeter = lambda w, h: 2.0 * (w + h)
rect_area = lambda w, h: float(w * h)
cuboid_volume = lambda w, h, d: float(w * h * d)
trapezoid_area = lambda a, b, h: ((a + b) * h) / 2.0
trapezoid_perimeter = lambda a, b, c, d: float(a + b + c + d)
polygon_perimeter = lambda n, s: float(n * s)
polygon_area = lambda n, s: (n * (s ** 2)) / (4.0 * math.tan(math.pi / n))
triangle_area = lambda b, h: 0.5 * b * h
triangle_perimeter = lambda a, b, c: float(a + b + c)

# --- Transpiled Program Statements ---
print('==================================================')
print('>>> BLANG ADVANCED MATH & GEOMETRY CALCULATION <<<')
print('==================================================')
bl_at_val_e = E
bl_at_ln_result = ln(bl_at_val_e)
bl_dollar_log10_val = log(1000)
bl_dollar_log2_val = log(64, 2)
print('--- 1. LOGARITHM & EXPONENTIAL ---')
print('ln(e)              =', bl_at_ln_result)
print('log10(1000)        =', bl_dollar_log10_val)
print('log2(64)           =', bl_dollar_log2_val)
bl_at_can_bac_2 = sqrt(144)
bl_at_can_bac_3 = cbrt(125)
bl_at_can_bac_4 = root(81, 4)
bl_dollar_luy_thua = pow(2, 10)
print('--- 2. ROOTS & POWERS ---')
print('sqrt(144)          =', bl_at_can_bac_2)
print('cbrt(125)          =', bl_at_can_bac_3)
print('root(81, 4)        =', bl_at_can_bac_4)
print('pow(2, 10)         =', bl_dollar_luy_thua)
bl_at_sin_90 = sind(90)
bl_at_cos_60 = cosd(60)
bl_at_tan_45 = tand(45)
bl_at_cot_45 = cotand(45)
print('--- 3. TRIGONOMETRY (GÓC & LƯỢNG GIÁC) ---')
print('sin(90 deg)        =', bl_at_sin_90)
print('cos(60 deg)        =', bl_at_cos_60)
print('tan(45 deg)        =', bl_at_tan_45)
print('cotan(45 deg)      =', bl_at_cot_45)
bl_at_ban_kinh = 5
_chu_vi_tron = circle_perimeter(bl_at_ban_kinh)
_dien_tich_tron = circle_area(bl_at_ban_kinh)
_the_tich_cau = sphere_volume(3)
_the_tich_tru = cylinder_volume(3, 10)
_the_tich_non = cone_volume(3, 10)
print('--- 4. HÌNH TRÒN, CẦU, TRỤ, NÓN ---')
print('Chu vi hình tròn (r=5)       =', _chu_vi_tron)
print('Diện tích hình tròn (r=5)    =', _dien_tich_tron)
print('Thể tích hình cầu (r=3)      =', _the_tich_cau)
print('Thể tích hình trụ (r=3, h=10)=', _the_tich_tru)
print('Thể tích hình nón (r=3, h=10)=', _the_tich_non)
bl_at_canh_vuong = 6
_chu_vi_vuong = square_perimeter(bl_at_canh_vuong)
_dien_tich_vuong = square_area(bl_at_canh_vuong)
_the_tich_lap_phuong = cube_volume(4)
print('--- 5. HÌNH VUÔNG & LẬP PHƯƠNG ---')
print('Chu vi hình vuông (a=6)      =', _chu_vi_vuong)
print('Diện tích hình vuông (a=6)   =', _dien_tich_vuong)
print('Thể tích lập phương (a=4)    =', _the_tich_lap_phuong)
_chu_vi_cn = rect_perimeter(8, 5)
_dien_tich_cn = rect_area(8, 5)
_the_tich_hop = cuboid_volume(4, 5, 6)
print('--- 6. HÌNH CHỮ NHẬT & HÌNH HỘP ---')
print('Chu vi hình chữ nhật (8x5)   =', _chu_vi_cn)
print('Diện tích hình chữ nhật (8x5)=', _dien_tich_cn)
print('Thể tích hình hộp (4x5x6)    =', _the_tich_hop)
_dien_tich_thang = trapezoid_area(6, 10, 4)
_chu_vi_thang = trapezoid_perimeter(6, 10, 5, 5)
_chu_vi_luc_giac = polygon_perimeter(6, 4)
_dien_tich_luc_giac = polygon_area(6, 4)
print('--- 7. HÌNH THANG & ĐA GIÁC ĐỀU ---')
print('Diện tích hình thang (6, 10, h=4)   =', _dien_tich_thang)
print('Chu vi hình thang (6, 10, 5, 5)     =', _chu_vi_thang)
print('Chu vi lục giác đều (n=6, s=4)      =', _chu_vi_luc_giac)
print('Diện tích lục giác đều (n=6, s=4)   =', _dien_tich_luc_giac)
print('==================================================')
print('>>> TẤT CẢ CÁC PHÉP TÍNH TOÁN HỌC ĐÃ HOÀN THÀNH <<<')
print('==================================================')
