import {
  ASTNode,
  ProgramNode,
  BlockNode,
  LiteralNode,
  IdentifierNode,
  VarDeclNode,
  AssignNode,
  BinaryOpNode,
  UnaryOpNode,
  ListNode,
  DictNode,
  IndexNode,
  CallNode,
  IfNode,
  WhileNode,
  ForNode,
  FunctionDefNode,
  ReturnNode,
  PrintNode,
  ExpressionStatementNode,
} from './types';

export function sanitizeIdentifierPy(name: string): string {
  if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    return name;
  }
  let res = name.replace(/@/g, 'bl_at_').replace(/\$/g, 'bl_dollar_');
  if (!/^[a-zA-Z_]/.test(res)) {
    res = '_' + res;
  }
  return res;
}

export class PythonCodeGenerator {
  private indentLevel = 0;
  private indentStr = '    ';

  private indent(): string {
    return this.indentStr.repeat(this.indentLevel);
  }

  public generate(ast: ProgramNode): string {
    const lines: string[] = [
      '# ==============================================================================',
      '# Auto-generated Python 3.x code transpiled from BLang',
      '# Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)',
      '# Target: Python 3.8+ Runtime Environment (AI, Scientific Computing, Backend)',
      '# ==============================================================================',
      'import sys',
      'import math',
      '',
      '# Runtime helper: Strict Type Safety Enforcer',
      'def _bl_strict_add(a, b):',
      '    if (isinstance(a, str) and isinstance(b, (int, float))) or (isinstance(a, (int, float)) and isinstance(b, str)):',
      "        raise TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +')",
      '    return a + b',
      '',
      '# Runtime helper: Math & Geometry Standard Functions',
      'PI = math.pi',
      'E = math.e',
      'sin = math.sin',
      'cos = math.cos',
      'tan = math.tan',
      'cotan = lambda x: 1.0 / math.tan(x)',
      'cot = cotan',
      'deg_to_rad = lambda d: d * (math.pi / 180.0)',
      'rad_to_deg = lambda r: r * (180.0 / math.pi)',
      'sind = lambda d: math.sin(d * (math.pi / 180.0))',
      'cosd = lambda d: math.cos(d * (math.pi / 180.0))',
      'tand = lambda d: math.tan(d * (math.pi / 180.0))',
      'cotand = lambda d: 1.0 / math.tan(d * (math.pi / 180.0))',
      'log = lambda x, base=10: math.log(x, base)',
      'ln = math.log',
      'log10 = math.log10',
      'log2 = math.log2',
      'sqrt = math.sqrt',
      'cbrt = lambda x: x ** (1.0 / 3.0)',
      'root = lambda x, n: x ** (1.0 / n)',
      'pow = math.pow',
      'power = pow',
      'circle_perimeter = lambda r: 2.0 * math.pi * r',
      'circle_circumference = circle_perimeter',
      'circle_area = lambda r: math.pi * (r ** 2)',
      'sphere_volume = lambda r: (4.0 / 3.0) * math.pi * (r ** 3)',
      'cylinder_volume = lambda r, h: math.pi * (r ** 2) * h',
      'cone_volume = lambda r, h: (1.0 / 3.0) * math.pi * (r ** 2) * h',
      'square_perimeter = lambda a: 4.0 * a',
      'square_area = lambda a: float(a * a)',
      'cube_volume = lambda a: float(a ** 3)',
      'rect_perimeter = lambda w, h: 2.0 * (w + h)',
      'rect_area = lambda w, h: float(w * h)',
      'cuboid_volume = lambda w, h, d: float(w * h * d)',
      'trapezoid_area = lambda a, b, h: ((a + b) * h) / 2.0',
      'trapezoid_perimeter = lambda a, b, c, d: float(a + b + c + d)',
      'polygon_perimeter = lambda n, s: float(n * s)',
      'polygon_area = lambda n, s: (n * (s ** 2)) / (4.0 * math.tan(math.pi / n))',
      'triangle_area = lambda b, h: 0.5 * b * h',
      'triangle_perimeter = lambda a, b, c: float(a + b + c)',
      '',
      '# --- Transpiled Program Statements ---',
    ];

    if (ast.statements.length === 0) {
      lines.push('pass');
    } else {
      for (const stmt of ast.statements) {
        const gen = this.genStatement(stmt);
        if (gen) lines.push(gen);
      }
    }

    return lines.join('\n') + '\n';
  }

  private genBlock(block: BlockNode): string {
    if (block.statements.length === 0) {
      return `${this.indent()}pass`;
    }
    const res: string[] = [];
    for (const s of block.statements) {
      const g = this.genStatement(s);
      if (g) res.push(g);
    }
    return res.join('\n');
  }

  private genStatement(node: ASTNode): string {
    switch (node.type) {
      case 'VarDecl': {
        const decl = node as VarDeclNode;
        const name = sanitizeIdentifierPy(decl.name);
        if (decl.initializer) {
          const val = this.genExpression(decl.initializer);
          return `${this.indent()}${name} = ${val}`;
        }
        return `${this.indent()}${name} = None`;
      }

      case 'Assign': {
        const assign = node as AssignNode;
        const tgt = this.genExpression(assign.target);
        const val = this.genExpression(assign.value);
        return `${this.indent()}${tgt} ${assign.operator} ${val}`;
      }

      case 'FunctionDef': {
        const fn = node as FunctionDefNode;
        const fnName = sanitizeIdentifierPy(fn.name);
        const params = fn.parameters.map((p) => sanitizeIdentifierPy(p)).join(', ');
        const hdr = `${this.indent()}def ${fnName}(${params}):`;
        this.indentLevel++;
        const body = this.genBlock(fn.body);
        this.indentLevel--;
        return `${hdr}\n${body}\n`;
      }

      case 'If': {
        const ifNode = node as IfNode;
        const cond = this.genExpression(ifNode.condition);
        const res: string[] = [`${this.indent()}if ${cond}:`];
        this.indentLevel++;
        res.push(this.genBlock(ifNode.thenBranch));
        this.indentLevel--;

        for (const branch of ifNode.elifBranches) {
          const c = this.genExpression(branch.condition);
          res.push(`${this.indent()}elif ${c}:`);
          this.indentLevel++;
          res.push(this.genBlock(branch.body));
          this.indentLevel--;
        }

        if (ifNode.elseBranch) {
          res.push(`${this.indent()}else:`);
          this.indentLevel++;
          res.push(this.genBlock(ifNode.elseBranch));
          this.indentLevel--;
        }

        return res.join('\n');
      }

      case 'While': {
        const w = node as WhileNode;
        const cond = this.genExpression(w.condition);
        const hdr = `${this.indent()}while ${cond}:`;
        this.indentLevel++;
        const body = this.genBlock(w.body);
        this.indentLevel--;
        return `${hdr}\n${body}`;
      }

      case 'For': {
        const f = node as ForNode;
        const varName = sanitizeIdentifierPy(f.variable);
        const iterExpr = this.genExpression(f.iterable);
        const hdr = `${this.indent()}for ${varName} in ${iterExpr}:`;
        this.indentLevel++;
        const body = this.genBlock(f.body);
        this.indentLevel--;
        return `${hdr}\n${body}`;
      }

      case 'Return': {
        const ret = node as ReturnNode;
        if (ret.expression) {
          return `${this.indent()}return ${this.genExpression(ret.expression)}`;
        }
        return `${this.indent()}return`;
      }

      case 'Break':
        return `${this.indent()}break`;

      case 'Continue':
        return `${this.indent()}continue`;

      case 'Print': {
        const p = node as PrintNode;
        const args = p.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${this.indent()}print(${args})`;
      }

      case 'Import': {
        const imp = node as any;
        const mod = imp.modulePath.replace('.bl', '').replace(/[\/\-]/g, '_');
        return `${this.indent()}# BLang Module Import: ${imp.modulePath}\ntry:\n    from ${mod} import *\nexcept ImportError:\n    pass`;
      }

      case 'Block':
        return this.genBlock(node as BlockNode);

      case 'ExpressionStatement': {
        const expr = (node as ExpressionStatementNode).expression;
        return `${this.indent()}${this.genExpression(expr)}`;
      }

      default:
        return '';
    }
  }

  private genExpression(node: ASTNode): string {
    switch (node.type) {
      case 'Literal': {
        const lit = node as LiteralNode;
        if (lit.litType === 'number') return String(lit.value);
        if (lit.litType === 'string') return JSON.stringify(lit.value);
        if (lit.litType === 'boolean') return lit.value ? 'True' : 'False';
        if (lit.litType === 'null') return 'None';
        return 'None';
      }

      case 'Identifier':
        return sanitizeIdentifierPy((node as IdentifierNode).name);

      case 'List': {
        const l = node as ListNode;
        const items = l.elements.map((e) => this.genExpression(e)).join(', ');
        return `[${items}]`;
      }

      case 'Dict': {
        const d = node as DictNode;
        const entries = d.entries
          .map((e) => `${this.genExpression(e.key)}: ${this.genExpression(e.value)}`)
          .join(', ');
        return `{${entries}}`;
      }

      case 'Index': {
        const idx = node as IndexNode;
        const tgt = this.genExpression(idx.target);
        const indexVal = this.genExpression(idx.index);
        return `${tgt}[${indexVal}]`;
      }

      case 'Call': {
        const call = node as CallNode;
        const callee = this.genExpression(call.callee);
        const args = call.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${callee}(${args})`;
      }

      case 'UnaryOp': {
        const un = node as UnaryOpNode;
        const op = un.operator === 'not' ? 'not ' : un.operator;
        const operand = this.genExpression(un.operand);
        return `(${op}${operand})`;
      }

      case 'BinaryOp': {
        const bin = node as BinaryOpNode;
        const left = this.genExpression(bin.left);
        const right = this.genExpression(bin.right);
        let op = bin.operator;
        if (op === 'and') op = 'and';
        else if (op === 'or') op = 'or';
        return `(${left} ${op} ${right})`;
      }

      default:
        return 'None';
    }
  }
}
