import {
  ASTNode,
  ProgramNode,
  BlockNode,
  LiteralNode,
  IdentifierNode,
  VarDeclNode,
  AssignNode,
  BinaryOpNode,
  UnaryOpNode,
  ListNode,
  DictNode,
  IndexNode,
  CallNode,
  IfNode,
  WhileNode,
  ForNode,
  FunctionDefNode,
  ReturnNode,
  PrintNode,
  ExpressionStatementNode,
} from './types';

export function sanitizeIdentifierJs(name: string): string {
  // In JavaScript, $ and _ are naturally valid identifier characters
  let res = name.replace(/@/g, '_at_');
  if (!/^[a-zA-Z_$]/.test(res)) {
    res = '_' + res;
  }
  return res;
}

export class JavaScriptCodeGenerator {
  private indentLevel = 0;
  private indentStr = '    ';
  private declaredVars = new Set<string>();

  private indent(): string {
    return this.indentStr.repeat(this.indentLevel);
  }

  public generate(ast: ProgramNode): string {
    this.declaredVars = new Set<string>();
    const lines: string[] = [
      '// ==============================================================================',
      '// Auto-generated JavaScript (ES6+) code transpiled from BLang',
      '// Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)',
      '// Target: Modern Web Browsers & Node.js Runtime (Web, Apps, Casual Games)',
      '// ==============================================================================',
      "'use strict';",
      '',
      '// Runtime helper: Strict Type Safety Enforcer (No coercion between string and number in arithmetic)',
      'function _bl_strict_add(a, b) {',
      "    if ((typeof a === 'string' && typeof b === 'number') || (typeof a === 'number' && typeof b === 'string')) {",
      "        throw new TypeError('BLang Strict TypeError: Cannot combine string and number using arithmetic operator +');",
      '    }',
      '    return a + b;',
      '}',
      '',
      '// Runtime helper: Math & Geometry Standard Functions',
      'const PI = Math.PI;',
      'const E = Math.E;',
      'const sin = (x) => Math.sin(x);',
      'const cos = (x) => Math.cos(x);',
      'const tan = (x) => Math.tan(x);',
      'const cotan = (x) => 1 / Math.tan(x);',
      'const cot = cotan;',
      'const deg_to_rad = (d) => d * (Math.PI / 180);',
      'const rad_to_deg = (r) => r * (180 / Math.PI);',
      'const sind = (d) => Math.sin(d * (Math.PI / 180));',
      'const cosd = (d) => Math.cos(d * (Math.PI / 180));',
      'const tand = (d) => Math.tan(d * (Math.PI / 180));',
      'const cotand = (d) => 1 / Math.tan(d * (Math.PI / 180));',
      'const log = (x, base) => (base !== undefined ? Math.log(x) / Math.log(base) : Math.log10(x));',
      'const ln = (x) => Math.log(x);',
      'const log10 = (x) => Math.log10(x);',
      'const log2 = (x) => Math.log2(x);',
      'const sqrt = (x) => Math.sqrt(x);',
      'const cbrt = (x) => Math.cbrt(x);',
      'const root = (x, n) => Math.pow(x, 1 / n);',
      'const pow = (b, e) => Math.pow(b, e);',
      'const power = pow;',
      'const circle_perimeter = (r) => 2 * Math.PI * r;',
      'const circle_circumference = circle_perimeter;',
      'const circle_area = (r) => Math.PI * r * r;',
      'const sphere_volume = (r) => (4 / 3) * Math.PI * Math.pow(r, 3);',
      'const cylinder_volume = (r, h) => Math.PI * r * r * h;',
      'const cone_volume = (r, h) => (1 / 3) * Math.PI * r * r * h;',
      'const square_perimeter = (a) => 4 * a;',
      'const square_area = (a) => a * a;',
      'const cube_volume = (a) => Math.pow(a, 3);',
      'const rect_perimeter = (w, h) => 2 * (w + h);',
      'const rect_area = (w, h) => w * h;',
      'const cuboid_volume = (w, h, d) => w * h * d;',
      'const trapezoid_area = (a, b, h) => ((a + b) * h) / 2;',
      'const trapezoid_perimeter = (a, b, c, d) => a + b + c + d;',
      'const polygon_perimeter = (n, s) => n * s;',
      'const polygon_area = (n, s) => (n * s * s) / (4 * Math.tan(Math.PI / n));',
      'const triangle_area = (b, h) => 0.5 * b * h;',
      'const triangle_perimeter = (a, b, c) => a + b + c;',
      '',
      '// --- Transpiled Program Statements ---',
    ];

    for (const stmt of ast.statements) {
      const gen = this.genStatement(stmt);
      if (gen) lines.push(gen);
    }

    return lines.join('\n') + '\n';
  }

  private genBlock(block: BlockNode): string {
    const res: string[] = [`${this.indent()}{`];
    this.indentLevel++;
    for (const s of block.statements) {
      const g = this.genStatement(s);
      if (g) res.push(g);
    }
    this.indentLevel--;
    res.push(`${this.indent()}}`);
    return res.join('\n');
  }

  private genStatement(node: ASTNode): string {
    switch (node.type) {
      case 'VarDecl': {
        const decl = node as VarDeclNode;
        const name = sanitizeIdentifierJs(decl.name);
        this.declaredVars.add(name);
        if (decl.initializer) {
          const val = this.genExpression(decl.initializer);
          return `${this.indent()}let ${name} = ${val};`;
        }
        return `${this.indent()}let ${name} = null;`;
      }

      case 'Assign': {
        const assign = node as AssignNode;
        const tgt = this.genExpression(assign.target);
        const val = this.genExpression(assign.value);
        if (assign.target.type === 'Identifier' && assign.operator === '=') {
          if (!this.declaredVars.has(tgt)) {
            this.declaredVars.add(tgt);
            return `${this.indent()}let ${tgt} = ${val};`;
          }
        }
        return `${this.indent()}${tgt} ${assign.operator} ${val};`;
      }

      case 'FunctionDef': {
        const fn = node as FunctionDefNode;
        const fnName = sanitizeIdentifierJs(fn.name);
        this.declaredVars.add(fnName);
        const params = fn.parameters.map((p) => sanitizeIdentifierJs(p));
        const prevDeclared = new Set(this.declaredVars);
        for (const p of params) this.declaredVars.add(p);
        const hdr = `${this.indent()}function ${fnName}(${params.join(', ')}) {`;
        this.indentLevel++;
        const bodyStmts: string[] = [];
        for (const s of fn.body.statements) {
          const g = this.genStatement(s);
          if (g) bodyStmts.push(g);
        }
        this.indentLevel--;
        this.declaredVars = prevDeclared;
        const bodyStr = bodyStmts.length > 0 ? bodyStmts.join('\n') : `${this.indent()}    // empty`;
        return `${hdr}\n${bodyStr}\n${this.indent()}}\n`;
      }

      case 'If': {
        const ifNode = node as IfNode;
        const cond = this.genExpression(ifNode.condition);
        const res: string[] = [`${this.indent()}if (${cond}) {`];
        this.indentLevel++;
        for (const s of ifNode.thenBranch.statements) {
          const g = this.genStatement(s);
          if (g) res.push(g);
        }
        this.indentLevel--;
        res.push(`${this.indent()}}`);

        for (const branch of ifNode.elifBranches) {
          const c = this.genExpression(branch.condition);
          res.push(`${this.indent()}else if (${c}) {`);
          this.indentLevel++;
          for (const s of branch.body.statements) {
            const g = this.genStatement(s);
            if (g) res.push(g);
          }
          this.indentLevel--;
          res.push(`${this.indent()}}`);
        }

        if (ifNode.elseBranch) {
          res.push(`${this.indent()}else {`);
          this.indentLevel++;
          for (const s of ifNode.elseBranch.statements) {
            const g = this.genStatement(s);
            if (g) res.push(g);
          }
          this.indentLevel--;
          res.push(`${this.indent()}}`);
        }

        return res.join('\n');
      }

      case 'While': {
        const w = node as WhileNode;
        const cond = this.genExpression(w.condition);
        const res: string[] = [`${this.indent()}while (${cond}) {`];
        this.indentLevel++;
        for (const s of w.body.statements) {
          const g = this.genStatement(s);
          if (g) res.push(g);
        }
        this.indentLevel--;
        res.push(`${this.indent()}}`);
        return res.join('\n');
      }

      case 'For': {
        const f = node as ForNode;
        const varName = sanitizeIdentifierJs(f.variable);
        const iterExpr = this.genExpression(f.iterable);
        const res: string[] = [`${this.indent()}for (const ${varName} of ${iterExpr}) {`];
        this.indentLevel++;
        for (const s of f.body.statements) {
          const g = this.genStatement(s);
          if (g) res.push(g);
        }
        this.indentLevel--;
        res.push(`${this.indent()}}`);
        return res.join('\n');
      }

      case 'Return': {
        const ret = node as ReturnNode;
        if (ret.expression) {
          return `${this.indent()}return ${this.genExpression(ret.expression)};`;
        }
        return `${this.indent()}return;`;
      }

      case 'Break':
        return `${this.indent()}break;`;

      case 'Continue':
        return `${this.indent()}continue;`;

      case 'Print': {
        const p = node as PrintNode;
        const args = p.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${this.indent()}console.log(${args});`;
      }

      case 'Import': {
        const imp = node as any;
        return `${this.indent()}// BLang Module Import: ${imp.modulePath};`;
      }

      case 'Block':
        return this.genBlock(node as BlockNode);

      case 'ExpressionStatement': {
        const expr = (node as ExpressionStatementNode).expression;
        return `${this.indent()}${this.genExpression(expr)};`;
      }

      default:
        return '';
    }
  }

  private genExpression(node: ASTNode): string {
    switch (node.type) {
      case 'Literal': {
        const lit = node as LiteralNode;
        if (lit.litType === 'number') return String(lit.value);
        if (lit.litType === 'string') return JSON.stringify(lit.value);
        if (lit.litType === 'boolean') return lit.value ? 'true' : 'false';
        if (lit.litType === 'null') return 'null';
        return 'null';
      }

      case 'Identifier': {
        const id = node as IdentifierNode;
        if (id.name === 'len') return '((x) => x.length)';
        return sanitizeIdentifierJs(id.name);
      }

      case 'List': {
        const l = node as ListNode;
        const items = l.elements.map((e) => this.genExpression(e)).join(', ');
        return `[${items}]`;
      }

      case 'Dict': {
        const d = node as DictNode;
        const entries = d.entries
          .map((e) => `${this.genExpression(e.key)}: ${this.genExpression(e.value)}`)
          .join(', ');
        return `{${entries}}`;
      }

      case 'Index': {
        const idx = node as IndexNode;
        const tgt = this.genExpression(idx.target);
        const indexVal = this.genExpression(idx.index);
        return `${tgt}[${indexVal}]`;
      }

      case 'Call': {
        const call = node as CallNode;
        const callee = this.genExpression(call.callee);
        const args = call.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${callee}(${args})`;
      }

      case 'UnaryOp': {
        const un = node as UnaryOpNode;
        const op = un.operator === 'not' ? '!' : un.operator;
        const operand = this.genExpression(un.operand);
        return `(${op}${operand})`;
      }

      case 'BinaryOp': {
        const bin = node as BinaryOpNode;
        const left = this.genExpression(bin.left);
        const right = this.genExpression(bin.right);
        let op = bin.operator;
        if (op === 'and') op = '&&';
        else if (op === 'or') op = '||';
        return `(${left} ${op} ${right})`;
      }

      default:
        return 'null';
    }
  }
}
