import {
  ASTNode,
  ProgramNode,
  BlockNode,
  LiteralNode,
  IdentifierNode,
  VarDeclNode,
  AssignNode,
  BinaryOpNode,
  UnaryOpNode,
  ListNode,
  DictNode,
  IndexNode,
  CallNode,
  IfNode,
  WhileNode,
  ForNode,
  FunctionDefNode,
  ReturnNode,
  PrintNode,
  ExpressionStatementNode,
} from './types';

export function sanitizeIdentifierPy(name: string): string {
  if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    return name;
  }
  let res = name.replace(/@/g, 'bl_at_').replace(/\$/g, 'bl_dollar_');
  if (!/^[a-zA-Z_]/.test(res)) {
    res = '_' + res;
  }
  return res;
}

function mapToPyType(t?: string): string {
  if (!t) return '';
  const lower = t.toLowerCase();
  if (lower === 'number' || lower === 'float' || lower === 'int') return 'float';
  if (lower === 'string' || lower === 'str') return 'str';
  if (lower === 'boolean' || lower === 'bool') return 'bool';
  if (lower === 'list') return 'list';
  if (lower === 'dict') return 'dict';
  if (lower === 'void') return 'None';
  return 'any';
}

export class PythonCodeGenerator {
  private indentLevel = 0;
  private indentStr = '    ';

  private indent(): string {
    return this.indentStr.repeat(this.indentLevel);
  }

  public generate(ast: ProgramNode): string {
    const lines: string[] = [
      '# ==============================================================================',
      '# Auto-generated Python 3.x code transpiled from BLang',
      '# Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)',
      '# Target: Python 3.8+ Runtime Environment (AI, Scientific Computing, Backend)',
      '# ==============================================================================',
      'import sys',
      'import math',
      'import time',
      'import random as _py_random',
      '',
      '# Runtime helper: Dynamic Addition / Concatenation',
      'def _bl_add(a, b):',
      '    if isinstance(a, str) or isinstance(b, str):',
      '        return str(a) + str(b)',
      '    return a + b',
      '',
      '# Runtime helper: Math & Geometry Standard Functions',
      'PI = math.pi',
      'E = math.e',
      '# Trigonometry (Degrees by default)',
      'sin = lambda d: math.sin(d * (math.pi / 180.0))',
      'cos = lambda d: math.cos(d * (math.pi / 180.0))',
      'tan = lambda d: math.tan(d * (math.pi / 180.0))',
      'cotan = lambda d: 1.0 / math.tan(d * (math.pi / 180.0))',
      'cot = cotan',
      'sind = sin',
      'cosd = cos',
      'tand = tan',
      'cotand = cotan',
      'sin_rad = math.sin',
      'cos_rad = math.cos',
      'tan_rad = math.tan',
      'cotan_rad = lambda r: 1.0 / math.tan(r)',
      'deg_to_rad = lambda d: d * (math.pi / 180.0)',
      'rad_to_deg = lambda r: r * (180.0 / math.pi)',
      'log = lambda x, base=10: math.log(x, base)',
      'ln = math.log',
      'log10 = math.log10',
      'log2 = math.log2',
      'sqrt = math.sqrt',
      'cbrt = lambda x: x ** (1.0 / 3.0)',
      'root = lambda x, n: x ** (1.0 / n)',
      'pow = math.pow',
      'power = pow',
      '# Geometry: Circle (circle / cir, c / C / perimeter, s / S / area)',
      'circle_c = lambda r: 2.0 * math.pi * r',
      'circle_C = circle_c',
      'cir_c = circle_c',
      'cir_C = circle_c',
      'circle_perimeter = circle_c',
      'cir_perimeter = circle_c',
      'circle_circumference = circle_c',
      'cir_circumference = circle_c',
      'circle_s = lambda r: math.pi * (r ** 2)',
      'circle_S = circle_s',
      'cir_s = circle_s',
      'cir_S = circle_s',
      'circle_area = circle_s',
      'cir_area = circle_s',
      '# Geometry: Sphere',
      'sphere_v = lambda r: (4.0 / 3.0) * math.pi * (r ** 3)',
      'sphere_V = sphere_v',
      'sphere_volume = sphere_v',
      'sphere_s = lambda r: 4.0 * math.pi * (r ** 2)',
      'sphere_S = sphere_s',
      'sphere_area = sphere_s',
      '# Geometry: Cylinder',
      'cylinder_v = lambda r, h: math.pi * (r ** 2) * h',
      'cylinder_V = cylinder_v',
      'cylinder_volume = cylinder_v',
      '# Geometry: Cone',
      'cone_v = lambda r, h: (1.0 / 3.0) * math.pi * (r ** 2) * h',
      'cone_V = cone_v',
      'cone_volume = cone_v',
      '# Geometry: Square (square / sq, c / C / perimeter, s / S / area)',
      'square_c = lambda a: 4.0 * a',
      'square_C = square_c',
      'sq_c = square_c',
      'sq_C = square_c',
      'square_perimeter = square_c',
      'sq_perimeter = square_c',
      'square_s = lambda a: float(a * a)',
      'square_S = square_s',
      'sq_s = square_s',
      'sq_S = square_s',
      'square_area = square_s',
      'sq_area = square_s',
      '# Geometry: Cube',
      'cube_v = lambda a: float(a ** 3)',
      'cube_V = cube_v',
      'cube_volume = cube_v',
      'cube_s = lambda a: 6.0 * (a ** 2)',
      'cube_S = cube_s',
      'cube_area = cube_s',
      '# Geometry: Rectangle (rect / rectangle, c / C / perimeter, s / S / area)',
      'rect_c = lambda w, h: 2.0 * (w + h)',
      'rect_C = rect_c',
      'rectangle_c = rect_c',
      'rectangle_C = rect_c',
      'rect_perimeter = rect_c',
      'rectangle_perimeter = rect_c',
      'rect_s = lambda w, h: float(w * h)',
      'rect_S = rect_s',
      'rectangle_s = rect_s',
      'rectangle_S = rect_s',
      'rect_area = rect_s',
      'rectangle_area = rect_s',
      '# Geometry: Cuboid',
      'cuboid_v = lambda w, h, d: float(w * h * d)',
      'cuboid_V = cuboid_v',
      'cuboid_volume = cuboid_v',
      '# Geometry: Trapezoid',
      'trapezoid_s = lambda a, b, h: ((a + b) * h) / 2.0',
      'trapezoid_S = trapezoid_s',
      'trapezoid_area = trapezoid_s',
      'trapezoid_c = lambda a, b, c, d: float(a + b + c + d)',
      'trapezoid_C = trapezoid_c',
      'trapezoid_perimeter = trapezoid_c',
      '# Geometry: Regular Polygon',
      'polygon_c = lambda n, s: float(n * s)',
      'polygon_C = polygon_c',
      'polygon_perimeter = polygon_c',
      'polygon_s = lambda n, s: (n * (s ** 2)) / (4.0 * math.tan(math.pi / n))',
      'polygon_S = polygon_s',
      'polygon_area = polygon_s',
      '# Geometry: Triangle (triangle / tri, c / C / perimeter, s / S / area)',
      'triangle_s = lambda b, h: 0.5 * b * h',
      'triangle_S = triangle_s',
      'triangle_area = triangle_s',
      'tri_s = triangle_s',
      'tri_S = triangle_s',
      'tri_area = triangle_s',
      'triangle_c = lambda a, b, c: float(a + b + c)',
      'triangle_C = triangle_c',
      'triangle_perimeter = triangle_c',
      'tri_c = triangle_c',
      'tri_C = triangle_c',
      'tri_perimeter = triangle_c',
      '# Standard Library: String Operations',
      'upper = lambda s: str(s).upper()',
      'lower = lambda s: str(s).lower()',
      'trim = lambda s: str(s).strip()',
      'replace = lambda s, o, n: str(s).replace(str(o), str(n))',
      'split = lambda s, d: str(s).split(str(d))',
      'join = lambda a, d="": d.join(str(x) for x in a) if isinstance(a, list) else str(a)',
      'contains = lambda s, sub: str(sub) in str(s)',
      '# Standard Library: List & Aggregation',
      'sum = lambda a: float(sum(float(x) for x in a)) if isinstance(a, list) and a else 0.0',
      'min_val = lambda a: float(min(float(x) for x in a)) if isinstance(a, list) and a else 0.0',
      'max_val = lambda a: float(max(float(x) for x in a)) if isinstance(a, list) and a else 0.0',
      'avg = lambda a: float(sum(float(x) for x in a)) / len(a) if isinstance(a, list) and a else 0.0',
      'reverse = lambda a: list(reversed(a)) if isinstance(a, list) else (str(a)[::-1] if isinstance(a, str) else a)',
      'time_now = lambda: float(time.time() * 1000.0)',
      'random = lambda a, b: _py_random.randint(int(min(a, b)), int(max(a, b))) if (isinstance(a, int) and isinstance(b, int)) else _py_random.uniform(min(a, b), max(a, b))',
      '',
      '# --- Transpiled Program Statements ---',
    ];

    if (ast.statements.length === 0) {
      lines.push('pass');
    } else {
      for (const stmt of ast.statements) {
        const gen = this.genStatement(stmt);
        if (gen) lines.push(gen);
      }
    }

    return lines.join('\n') + '\n';
  }

  private genBlock(block: BlockNode): string {
    if (block.statements.length === 0) {
      return `${this.indent()}pass`;
    }
    const res: string[] = [];
    for (const s of block.statements) {
      const g = this.genStatement(s);
      if (g) res.push(g);
    }
    return res.join('\n');
  }

  private genStatement(node: ASTNode): string {
    switch (node.type) {
      case 'VarDecl': {
        const decl = node as VarDeclNode;
        const name = sanitizeIdentifierPy(decl.name);
        const typeHint = decl.typeAnnotation ? `: ${mapToPyType(decl.typeAnnotation)}` : '';
        if (decl.initializer) {
          const val = this.genExpression(decl.initializer);
          return `${this.indent()}${name}${typeHint} = ${val}`;
        }
        return `${this.indent()}${name}${typeHint} = None`;
      }

      case 'Destructure': {
        const d = node as any;
        const sanitized = d.names.map(sanitizeIdentifierPy);
        if (d.kind === 'array') {
          return `${this.indent()}${sanitized.join(', ')} = ${this.genExpression(d.value)}`;
        } else {
          const valExpr = this.genExpression(d.value);
          const lines = [`${this.indent()}_dict_destruct = ${valExpr}`];
          for (const name of d.names) {
            const sName = sanitizeIdentifierPy(name);
            lines.push(`${this.indent()}${sName} = _dict_destruct.get("${name}", None)`);
          }
          return lines.join('\n');
        }
      }

      case 'Assign': {
        const assign = node as AssignNode;
        const tgt = this.genExpression(assign.target);
        const val = this.genExpression(assign.value);
        return `${this.indent()}${tgt} ${assign.operator} ${val}`;
      }

      case 'FunctionDef': {
        const fn = node as FunctionDefNode;
        const fnName = sanitizeIdentifierPy(fn.name);
        let params: string;
        if (fn.paramDetails && fn.paramDetails.length > 0) {
          params = fn.paramDetails
            .map((p) => {
              const pName = sanitizeIdentifierPy(p.name);
              return p.typeAnnotation ? `${pName}: ${mapToPyType(p.typeAnnotation)}` : pName;
            })
            .join(', ');
        } else {
          params = fn.parameters.map((p) => sanitizeIdentifierPy(p)).join(', ');
        }
        const retHint = fn.returnType ? ` -> ${mapToPyType(fn.returnType)}` : '';
        const hdr = `${this.indent()}def ${fnName}(${params})${retHint}:`;
        this.indentLevel++;
        const body = this.genBlock(fn.body);
        this.indentLevel--;
        return `${hdr}\n${body}\n`;
      }

      case 'If': {
        const ifNode = node as IfNode;
        const cond = this.genExpression(ifNode.condition);
        const res: string[] = [`${this.indent()}if ${cond}:`];
        this.indentLevel++;
        res.push(this.genBlock(ifNode.thenBranch));
        this.indentLevel--;

        for (const branch of ifNode.elifBranches) {
          const c = this.genExpression(branch.condition);
          res.push(`${this.indent()}elif ${c}:`);
          this.indentLevel++;
          res.push(this.genBlock(branch.body));
          this.indentLevel--;
        }

        if (ifNode.elseBranch) {
          res.push(`${this.indent()}else:`);
          this.indentLevel++;
          res.push(this.genBlock(ifNode.elseBranch));
          this.indentLevel--;
        }

        return res.join('\n');
      }

      case 'While': {
        const w = node as WhileNode;
        const cond = this.genExpression(w.condition);
        const hdr = `${this.indent()}while ${cond}:`;
        this.indentLevel++;
        const body = this.genBlock(w.body);
        this.indentLevel--;
        return `${hdr}\n${body}`;
      }

      case 'For': {
        const f = node as ForNode;
        const varName = sanitizeIdentifierPy(f.variable);
        const iterExpr = this.genExpression(f.iterable);
        const hdr = `${this.indent()}for ${varName} in ${iterExpr}:`;
        this.indentLevel++;
        const body = this.genBlock(f.body);
        this.indentLevel--;
        return `${hdr}\n${body}`;
      }

      case 'Return': {
        const ret = node as ReturnNode;
        if (ret.expression) {
          return `${this.indent()}return ${this.genExpression(ret.expression)}`;
        }
        return `${this.indent()}return`;
      }

      case 'Break':
        return `${this.indent()}break`;

      case 'Continue':
        return `${this.indent()}continue`;

      case 'Print': {
        const p = node as PrintNode;
        const args = p.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${this.indent()}print(${args})`;
      }

      case 'TryCatch': {
        const tc = node as any;
        const errVar = tc.errorVar ? sanitizeIdentifierPy(tc.errorVar) : '_err';
        const tryBody = this.genBlock(tc.tryBlock);
        const catchBody = this.genBlock(tc.catchBlock);
        return `${this.indent()}try:\n${tryBody}\n${this.indent()}except Exception as ${errVar}:\n${catchBody}`;
      }

      case 'Throw': {
        const th = node as any;
        return `${this.indent()}raise Exception(${this.genExpression(th.expression)})`;
      }

      case 'Match': {
        const m = node as any;
        const disc = this.genExpression(m.discriminant);
        const lines: string[] = [`${this.indent()}match ${disc}:`];
        this.indentLevel++;
        for (const c of m.cases) {
          lines.push(`${this.indent()}case ${this.genExpression(c.pattern)}:`);
          this.indentLevel++;
          for (const s of c.body.statements) {
            const g = this.genStatement(s);
            if (g) lines.push(g);
          }
          if (c.body.statements.length === 0) lines.push(`${this.indent()}pass`);
          this.indentLevel--;
        }
        if (m.defaultCase) {
          lines.push(`${this.indent()}case _:`);
          this.indentLevel++;
          for (const s of m.defaultCase.statements) {
            const g = this.genStatement(s);
            if (g) lines.push(g);
          }
          if (m.defaultCase.statements.length === 0) lines.push(`${this.indent()}pass`);
          this.indentLevel--;
        }
        this.indentLevel--;
        return lines.join('\n');
      }

      case 'Import': {
        const imp = node as any;
        const mod = imp.modulePath.replace('.bl', '').replace(/[\/\-]/g, '_');
        return `${this.indent()}# BLang Module Import: ${imp.modulePath}\ntry:\n    from ${mod} import *\nexcept ImportError:\n    pass`;
      }

      case 'Block':
        return this.genBlock(node as BlockNode);

      case 'ExpressionStatement': {
        const expr = (node as ExpressionStatementNode).expression;
        return `${this.indent()}${this.genExpression(expr)}`;
      }

      default:
        return '';
    }
  }

  private genExpression(node: ASTNode): string {
    switch (node.type) {
      case 'Literal': {
        const lit = node as LiteralNode;
        if (lit.litType === 'number') return String(lit.value);
        if (lit.litType === 'string') return JSON.stringify(lit.value);
        if (lit.litType === 'boolean') return lit.value ? 'True' : 'False';
        if (lit.litType === 'null') return 'None';
        return 'None';
      }

      case 'Identifier':
        return sanitizeIdentifierPy((node as IdentifierNode).name);

      case 'List': {
        const l = node as ListNode;
        const items = l.elements.map((e) => this.genExpression(e)).join(', ');
        return `[${items}]`;
      }

      case 'Dict': {
        const d = node as DictNode;
        const entries = d.entries
          .map((e) => `${this.genExpression(e.key)}: ${this.genExpression(e.value)}`)
          .join(', ');
        return `{${entries}}`;
      }

      case 'Index': {
        const idx = node as IndexNode;
        const tgt = this.genExpression(idx.target);
        const indexVal = this.genExpression(idx.index);
        return `${tgt}[${indexVal}]`;
      }

      case 'Call': {
        const call = node as CallNode;
        const callee = this.genExpression(call.callee);
        const args = call.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${callee}(${args})`;
      }

      case 'UnaryOp': {
        const un = node as UnaryOpNode;
        const op = un.operator === 'not' ? 'not ' : un.operator;
        const operand = this.genExpression(un.operand);
        return `(${op}${operand})`;
      }

      case 'BinaryOp': {
        const bin = node as BinaryOpNode;
        const left = this.genExpression(bin.left);
        const right = this.genExpression(bin.right);
        if (bin.operator === '+') {
          return `_bl_add(${left}, ${right})`;
        }
        if (bin.operator === '??') {
          return `(${left} if (${left}) is not None else ${right})`;
        }
        let op = bin.operator;
        if (op === 'and') op = 'and';
        else if (op === 'or') op = 'or';
        return `(${left} ${op} ${right})`;
      }

      case 'Range': {
        const r = node as any;
        const start = this.genExpression(r.start);
        const end = this.genExpression(r.end);
        return `list(range(int(${start}), int(${end}) + 1))`;
      }

      case 'Pipeline': {
        const p = node as any;
        const left = this.genExpression(p.left);
        if (p.target.type === 'Identifier') {
          return `${sanitizeIdentifierPy(p.target.name)}(${left})`;
        }
        if (p.target.type === 'Call') {
          const fn = this.genExpression(p.target.callee);
          const args = p.target.arguments.map((a: any) => this.genExpression(a));
          return `${fn}(${[left, ...args].join(', ')})`;
        }
        return left;
      }

      case 'InterpolatedString': {
        const isNode = node as any;
        let pyStr = 'f"';
        for (const part of isNode.parts) {
          if (part.type === 'Literal' && part.litType === 'string') {
            pyStr += String(part.value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/{/g, '{{').replace(/}/g, '}}');
          } else {
            pyStr += '{' + this.genExpression(part) + '}';
          }
        }
        pyStr += '"';
        return pyStr;
      }

      default:
        return 'None';
    }
  }
}
