import {
  ASTNode,
  ProgramNode,
  BlockNode,
  LiteralNode,
  IdentifierNode,
  VarDeclNode,
  AssignNode,
  BinaryOpNode,
  UnaryOpNode,
  ListNode,
  DictNode,
  IndexNode,
  CallNode,
  IfNode,
  WhileNode,
  ForNode,
  FunctionDefNode,
  ReturnNode,
  PrintNode,
  ExpressionStatementNode,
} from './types';

export function sanitizeIdentifierJs(name: string): string {
  // In JavaScript, $ and _ are naturally valid identifier characters
  let res = name.replace(/@/g, '_at_');
  if (!/^[a-zA-Z_$]/.test(res)) {
    res = '_' + res;
  }
  return res;
}

export class JavaScriptCodeGenerator {
  private indentLevel = 0;
  private indentStr = '    ';
  private declaredVars = new Set<string>();

  private indent(): string {
    return this.indentStr.repeat(this.indentLevel);
  }

  public generate(ast: ProgramNode): string {
    this.declaredVars = new Set<string>();
    const lines: string[] = [
      '// ==============================================================================',
      '// Auto-generated JavaScript (ES6+) code transpiled from BLang',
      '// Generated by BLang Multi-Pass Transpiler (Layer 5 Code Generator)',
      '// Target: Modern Web Browsers & Node.js Runtime (Web, Apps, Casual Games)',
      '// ==============================================================================',
      "'use strict';",
      '',
      '// Runtime helper: Math & Geometry Standard Functions',
      'const PI = Math.PI;',
      'const E = Math.E;',
      '// Trigonometry (Degrees by default)',
      'const sin = (d) => Math.sin(d * (Math.PI / 180));',
      'const cos = (d) => Math.cos(d * (Math.PI / 180));',
      'const tan = (d) => Math.tan(d * (Math.PI / 180));',
      'const cotan = (d) => 1 / Math.tan(d * (Math.PI / 180));',
      'const cot = cotan;',
      'const sind = sin;',
      'const cosd = cos;',
      'const tand = tan;',
      'const cotand = cotan;',
      'const sin_rad = (r) => Math.sin(r);',
      'const cos_rad = (r) => Math.cos(r);',
      'const tan_rad = (r) => Math.tan(r);',
      'const cotan_rad = (r) => 1 / Math.tan(r);',
      'const deg_to_rad = (d) => d * (Math.PI / 180);',
      'const rad_to_deg = (r) => r * (180 / Math.PI);',
      'const log = (x, base) => (base !== undefined ? Math.log(x) / Math.log(base) : Math.log10(x));',
      'const ln = (x) => Math.log(x);',
      'const log10 = (x) => Math.log10(x);',
      'const log2 = (x) => Math.log2(x);',
      'const sqrt = (x) => Math.sqrt(x);',
      'const cbrt = (x) => Math.cbrt(x);',
      'const root = (x, n) => Math.pow(x, 1 / n);',
      'const pow = (b, e) => Math.pow(b, e);',
      'const power = pow;',
      '// Geometry: Circle (circle / cir, c / C / perimeter, s / S / area)',
      'const circle_c = (r) => 2 * Math.PI * r;',
      'const circle_C = circle_c;',
      'const cir_c = circle_c;',
      'const cir_C = circle_c;',
      'const circle_perimeter = circle_c;',
      'const cir_perimeter = circle_c;',
      'const circle_circumference = circle_c;',
      'const cir_circumference = circle_c;',
      'const circle_s = (r) => Math.PI * r * r;',
      'const circle_S = circle_s;',
      'const cir_s = circle_s;',
      'const cir_S = circle_s;',
      'const circle_area = circle_s;',
      'const cir_area = circle_s;',
      '// Geometry: Sphere',
      'const sphere_v = (r) => (4 / 3) * Math.PI * Math.pow(r, 3);',
      'const sphere_V = sphere_v;',
      'const sphere_volume = sphere_v;',
      'const sphere_s = (r) => 4 * Math.PI * Math.pow(r, 2);',
      'const sphere_S = sphere_s;',
      'const sphere_area = sphere_s;',
      '// Geometry: Cylinder',
      'const cylinder_v = (r, h) => Math.PI * r * r * h;',
      'const cylinder_V = cylinder_v;',
      'const cylinder_volume = cylinder_v;',
      '// Geometry: Cone',
      'const cone_v = (r, h) => (1 / 3) * Math.PI * r * r * h;',
      'const cone_V = cone_v;',
      'const cone_volume = cone_v;',
      '// Geometry: Square (square / sq, c / C / perimeter, s / S / area)',
      'const square_c = (a) => 4 * a;',
      'const square_C = square_c;',
      'const sq_c = square_c;',
      'const sq_C = square_c;',
      'const square_perimeter = square_c;',
      'const sq_perimeter = square_c;',
      'const square_s = (a) => a * a;',
      'const square_S = square_s;',
      'const sq_s = square_s;',
      'const sq_S = square_s;',
      'const square_area = square_s;',
      'const sq_area = square_s;',
      '// Geometry: Cube',
      'const cube_v = (a) => Math.pow(a, 3);',
      'const cube_V = cube_v;',
      'const cube_volume = cube_v;',
      'const cube_s = (a) => 6 * a * a;',
      'const cube_S = cube_s;',
      'const cube_area = cube_s;',
      '// Geometry: Rectangle (rect / rectangle, c / C / perimeter, s / S / area)',
      'const rect_c = (w, h) => 2 * (w + h);',
      'const rect_C = rect_c;',
      'const rectangle_c = rect_c;',
      'const rectangle_C = rect_c;',
      'const rect_perimeter = rect_c;',
      'const rectangle_perimeter = rect_c;',
      'const rect_s = (w, h) => w * h;',
      'const rect_S = rect_s;',
      'const rectangle_s = rect_s;',
      'const rectangle_S = rect_s;',
      'const rect_area = rect_s;',
      'const rectangle_area = rect_s;',
      '// Geometry: Cuboid',
      'const cuboid_v = (w, h, d) => w * h * d;',
      'const cuboid_V = cuboid_v;',
      'const cuboid_volume = cuboid_v;',
      '// Geometry: Trapezoid',
      'const trapezoid_s = (a, b, h) => ((a + b) * h) / 2;',
      'const trapezoid_S = trapezoid_s;',
      'const trapezoid_area = trapezoid_s;',
      'const trapezoid_c = (a, b, c, d) => a + b + c + d;',
      'const trapezoid_C = trapezoid_c;',
      'const trapezoid_perimeter = trapezoid_c;',
      '// Geometry: Regular Polygon',
      'const polygon_c = (n, s) => n * s;',
      'const polygon_C = polygon_c;',
      'const polygon_perimeter = polygon_c;',
      'const polygon_s = (n, s) => (n * s * s) / (4 * Math.tan(Math.PI / n));',
      'const polygon_S = polygon_s;',
      'const polygon_area = polygon_s;',
      '// Geometry: Triangle (triangle / tri, c / C / perimeter, s / S / area)',
      'const triangle_s = (b, h) => 0.5 * b * h;',
      'const triangle_S = triangle_s;',
      'const triangle_area = triangle_s;',
      'const tri_s = triangle_s;',
      'const tri_S = triangle_s;',
      'const tri_area = triangle_s;',
      'const triangle_c = (a, b, c) => a + b + c;',
      'const triangle_C = triangle_c;',
      'const triangle_perimeter = triangle_c;',
      'const tri_c = triangle_c;',
      'const tri_C = triangle_c;',
      'const tri_perimeter = triangle_c;',
      '// Standard Library: String Operations',
      'const upper = (s) => String(s).toUpperCase();',
      'const lower = (s) => String(s).toLowerCase();',
      'const trim = (s) => String(s).trim();',
      'const replace = (s, o, n) => String(s).split(String(o)).join(String(n));',
      'const split = (s, d) => String(s).split(String(d));',
      'const join = (a, d) => Array.isArray(a) ? a.join(d ?? "") : String(a);',
      'const contains = (s, sub) => String(s).includes(String(sub));',
      '// Standard Library: List & Aggregation',
      'const sum = (a) => Array.isArray(a) ? a.reduce((acc, c) => acc + Number(c), 0) : 0;',
      'const min_val = (a) => Array.isArray(a) && a.length > 0 ? Math.min(...a.map(Number)) : 0;',
      'const max_val = (a) => Array.isArray(a) && a.length > 0 ? Math.max(...a.map(Number)) : 0;',
      'const avg = (a) => Array.isArray(a) && a.length > 0 ? a.reduce((acc, c) => acc + Number(c), 0) / a.length : 0;',
      'const reverse = (a) => Array.isArray(a) ? [...a].reverse() : (typeof a === "string" ? a.split("").reverse().join("") : a);',
      'const time_now = () => Date.now();',
      'const random = (a, b) => { const lo = Math.min(Number(a), Number(b)); const hi = Math.max(Number(a), Number(b)); return Number.isInteger(Number(a)) && Number.isInteger(Number(b)) ? Math.floor(Math.random() * (hi - lo + 1)) + lo : Math.random() * (hi - lo) + lo; };',
      '',
      '// --- Transpiled Program Statements ---',
    ];

    for (const stmt of ast.statements) {
      const gen = this.genStatement(stmt);
      if (gen) lines.push(gen);
    }

    return lines.join('\n') + '\n';
  }

  private genBlock(block: BlockNode): string {
    const res: string[] = [`${this.indent()}{`];
    this.indentLevel++;
    for (const s of block.statements) {
      const g = this.genStatement(s);
      if (g) res.push(g);
    }
    this.indentLevel--;
    res.push(`${this.indent()}}`);
    return res.join('\n');
  }

  private genStatement(node: ASTNode): string {
    switch (node.type) {
      case 'VarDecl': {
        const decl = node as VarDeclNode;
        const name = sanitizeIdentifierJs(decl.name);
        this.declaredVars.add(name);
        if (decl.initializer) {
          const val = this.genExpression(decl.initializer);
          return `${this.indent()}let ${name} = ${val};`;
        }
        return `${this.indent()}let ${name} = null;`;
      }

      case 'Assign': {
        const assign = node as AssignNode;
        const tgt = this.genExpression(assign.target);
        const val = this.genExpression(assign.value);
        if (assign.target.type === 'Identifier' && assign.operator === '=') {
          if (!this.declaredVars.has(tgt)) {
            this.declaredVars.add(tgt);
            return `${this.indent()}let ${tgt} = ${val};`;
          }
        }
        return `${this.indent()}${tgt} ${assign.operator} ${val};`;
      }

      case 'FunctionDef': {
        const fn = node as FunctionDefNode;
        const fnName = sanitizeIdentifierJs(fn.name);
        this.declaredVars.add(fnName);
        const params = fn.parameters.map((p) => sanitizeIdentifierJs(p));
        const prevDeclared = new Set(this.declaredVars);
        for (const p of params) this.declaredVars.add(p);
        const hdr = `${this.indent()}function ${fnName}(${params.join(', ')}) {`;
        this.indentLevel++;
        const bodyStmts: string[] = [];
        for (const s of fn.body.statements) {
          const g = this.genStatement(s);
          if (g) bodyStmts.push(g);
        }
        this.indentLevel--;
        this.declaredVars = prevDeclared;
        const bodyStr = bodyStmts.length > 0 ? bodyStmts.join('\n') : `${this.indent()}    // empty`;
        return `${hdr}\n${bodyStr}\n${this.indent()}}\n`;
      }

      case 'If': {
        const ifNode = node as IfNode;
        const cond = this.genExpression(ifNode.condition);
        const res: string[] = [`${this.indent()}if (${cond}) {`];
        this.indentLevel++;
        for (const s of ifNode.thenBranch.statements) {
          const g = this.genStatement(s);
          if (g) res.push(g);
        }
        this.indentLevel--;
        res.push(`${this.indent()}}`);

        for (const branch of ifNode.elifBranches) {
          const c = this.genExpression(branch.condition);
          res.push(`${this.indent()}else if (${c}) {`);
          this.indentLevel++;
          for (const s of branch.body.statements) {
            const g = this.genStatement(s);
            if (g) res.push(g);
          }
          this.indentLevel--;
          res.push(`${this.indent()}}`);
        }

        if (ifNode.elseBranch) {
          res.push(`${this.indent()}else {`);
          this.indentLevel++;
          for (const s of ifNode.elseBranch.statements) {
            const g = this.genStatement(s);
            if (g) res.push(g);
          }
          this.indentLevel--;
          res.push(`${this.indent()}}`);
        }

        return res.join('\n');
      }

      case 'While': {
        const w = node as WhileNode;
        const cond = this.genExpression(w.condition);
        const res: string[] = [`${this.indent()}while (${cond}) {`];
        this.indentLevel++;
        for (const s of w.body.statements) {
          const g = this.genStatement(s);
          if (g) res.push(g);
        }
        this.indentLevel--;
        res.push(`${this.indent()}}`);
        return res.join('\n');
      }

      case 'For': {
        const f = node as ForNode;
        const varName = sanitizeIdentifierJs(f.variable);
        const iterExpr = this.genExpression(f.iterable);
        const res: string[] = [`${this.indent()}for (const ${varName} of ${iterExpr}) {`];
        this.indentLevel++;
        for (const s of f.body.statements) {
          const g = this.genStatement(s);
          if (g) res.push(g);
        }
        this.indentLevel--;
        res.push(`${this.indent()}}`);
        return res.join('\n');
      }

      case 'Return': {
        const ret = node as ReturnNode;
        if (ret.expression) {
          return `${this.indent()}return ${this.genExpression(ret.expression)};`;
        }
        return `${this.indent()}return;`;
      }

      case 'Break':
        return `${this.indent()}break;`;

      case 'Continue':
        return `${this.indent()}continue;`;

      case 'TryCatch': {
        const tc = node as any;
        const errVar = tc.errorVar ? sanitizeIdentifierJs(tc.errorVar) : '_err';
        const tryBody = this.genBlock(tc.tryBlock);
        const catchBody = this.genBlock(tc.catchBlock);
        return `${this.indent()}try {\n${tryBody}\n${this.indent()}} catch (${errVar}) {\n${catchBody}\n${this.indent()}}`;
      }

      case 'Throw': {
        const th = node as any;
        return `${this.indent()}throw ${this.genExpression(th.expression)};`;
      }

      case 'Print': {
        const p = node as PrintNode;
        const args = p.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${this.indent()}console.log(${args});`;
      }

      case 'Import': {
        const imp = node as any;
        return `${this.indent()}// BLang Module Import: ${imp.modulePath};`;
      }

      case 'Block':
        return this.genBlock(node as BlockNode);

      case 'ExpressionStatement': {
        const expr = (node as ExpressionStatementNode).expression;
        return `${this.indent()}${this.genExpression(expr)};`;
      }

      default:
        return '';
    }
  }

  private genExpression(node: ASTNode): string {
    switch (node.type) {
      case 'Literal': {
        const lit = node as LiteralNode;
        if (lit.litType === 'number') return String(lit.value);
        if (lit.litType === 'string') return JSON.stringify(lit.value);
        if (lit.litType === 'boolean') return lit.value ? 'true' : 'false';
        if (lit.litType === 'null') return 'null';
        return 'null';
      }

      case 'Identifier': {
        const id = node as IdentifierNode;
        if (id.name === 'len') return '((x) => x.length)';
        return sanitizeIdentifierJs(id.name);
      }

      case 'List': {
        const l = node as ListNode;
        const items = l.elements.map((e) => this.genExpression(e)).join(', ');
        return `[${items}]`;
      }

      case 'Dict': {
        const d = node as DictNode;
        const entries = d.entries
          .map((e) => `${this.genExpression(e.key)}: ${this.genExpression(e.value)}`)
          .join(', ');
        return `{${entries}}`;
      }

      case 'Index': {
        const idx = node as IndexNode;
        const tgt = this.genExpression(idx.target);
        const indexVal = this.genExpression(idx.index);
        return `${tgt}[${indexVal}]`;
      }

      case 'Call': {
        const call = node as CallNode;
        const callee = this.genExpression(call.callee);
        const args = call.arguments.map((a) => this.genExpression(a)).join(', ');
        return `${callee}(${args})`;
      }

      case 'UnaryOp': {
        const un = node as UnaryOpNode;
        const op = un.operator === 'not' ? '!' : un.operator;
        const operand = this.genExpression(un.operand);
        return `(${op}${operand})`;
      }

      case 'BinaryOp': {
        const bin = node as BinaryOpNode;
        const left = this.genExpression(bin.left);
        const right = this.genExpression(bin.right);
        let op = bin.operator;
        if (op === 'and') op = '&&';
        else if (op === 'or') op = '||';
        return `(${left} ${op} ${right})`;
      }

      default:
        return 'null';
    }
  }
}
